namespace CanisUIForge.Generation.Output;

public static class GeneratedFileHeader
{
    private const string Marker = "<auto-generated>";

    private static readonly string CSharpHeader = string.Join(
        Environment.NewLine,
        "// <auto-generated>",
        "// This file was generated by CanisUIForge. Do not modify manually.",
        "// Changes will be overwritten on next generation.",
        "// </auto-generated>",
        "");

    private static readonly string RazorHeader = string.Join(
        Environment.NewLine,
        "@* <auto-generated>",
        "   This file was generated by CanisUIForge. Do not modify manually.",
        "   Changes will be overwritten on next generation.",
        "   </auto-generated> *@",
        "");

    private static readonly string XmlHeader = string.Join(
        Environment.NewLine,
        "<!-- <auto-generated>",
        "     This file was generated by CanisUIForge. Do not modify manually.",
        "     Changes will be overwritten on next generation.",
        "     </auto-generated> -->",
        "");

    private static readonly string CssHeader = string.Join(
        Environment.NewLine,
        "/* <auto-generated>",
        "   This file was generated by CanisUIForge. Do not modify manually.",
        "   Changes will be overwritten on next generation.",
        "   </auto-generated> */",
        "");

    public static string AddHeader(string filePath, string content)
    {
        if (string.IsNullOrWhiteSpace(filePath))
            throw new ArgumentException("File path must not be null or empty.", nameof(filePath));

        string extension = Path.GetExtension(filePath).ToLowerInvariant();
        string? header = GetHeaderForExtension(extension);

        if (header is null)
            return content;

        return header + Environment.NewLine + content;
    }

    public static bool IsGeneratedFile(string filePath)
    {
        if (string.IsNullOrWhiteSpace(filePath))
            return false;

        if (!File.Exists(filePath))
            return false;

        using (StreamReader reader = new StreamReader(filePath))
        {
            for (int i = 0; i < 5; i++)
            {
                string? line = reader.ReadLine();

                if (line is null)
                    break;

                if (line.Contains(Marker, StringComparison.Ordinal))
                    return true;
            }
        }

        return false;
    }

    public static bool SupportsHeader(string filePath)
    {
        if (string.IsNullOrWhiteSpace(filePath))
            return false;

        string extension = Path.GetExtension(filePath).ToLowerInvariant();
        return GetHeaderForExtension(extension) is not null;
    }

    private static string? GetHeaderForExtension(string extension)
    {
        return extension switch
        {
            ".cs" => CSharpHeader,
            ".razor" => RazorHeader,
            ".css" => CssHeader,
            ".csproj" => XmlHeader,
            ".props" => XmlHeader,
            ".targets" => XmlHeader,
            ".xaml" => XmlHeader,
            ".html" => XmlHeader,
            ".xml" => XmlHeader,
            _ => null
        };
    }
}
