namespace CanisUIForge.Generation.Templating;

public static class GeneratedFileHeader
{
    public const string CSharp =
        "// <auto-generated>\n" +
        "// AUTO-GENERATED – DO NOT MODIFY\n" +
        "// Any changes to this file will be overwritten during regeneration.\n" +
        "// </auto-generated>\n";

    public const string Razor =
        "@* AUTO-GENERATED – DO NOT MODIFY *@\n" +
        "@* Any changes to this file will be overwritten during regeneration. *@\n";

    public const string Css =
        "/* AUTO-GENERATED – DO NOT MODIFY */\n" +
        "/* Any changes to this file will be overwritten during regeneration. */\n";

    public const string Xml =
        "<!-- AUTO-GENERATED – DO NOT MODIFY -->\n" +
        "<!-- Any changes to this file will be overwritten during regeneration. -->\n";
}
