using CanisUIForge.Generation.Models;
using CanisUIForge.Generation.Output;
using CanisUIForge.Generation.Templating;

namespace CanisUIForge.Blazor.Generators;

public class BlazorBootstrapGenerator
{
    private readonly IFileWriter _fileWriter;
    private readonly ITemplateEngine _templateEngine;

    public BlazorBootstrapGenerator(IFileWriter fileWriter, ITemplateEngine templateEngine)
    {
        _fileWriter = fileWriter ?? throw new ArgumentNullException(nameof(fileWriter));
        _templateEngine = templateEngine ?? throw new ArgumentNullException(nameof(templateEngine));
    }

    public async Task GenerateAsync(GenerationPlan plan, string blazorProjectPath)
    {
        Dictionary<string, string> replacements = new Dictionary<string, string>
        {
            { "NamespaceRoot", plan.NamespaceRoot },
            { "SolutionName", plan.SolutionName }
        };

        await GenerateGlobalUsingsAsync(plan, blazorProjectPath, replacements);
        await GenerateImportsRazorAsync(blazorProjectPath, replacements);
        await GenerateAppRazorAsync(blazorProjectPath, replacements);
        await GenerateRoutesRazorAsync(blazorProjectPath, replacements);
        await GenerateProgramCsAsync(blazorProjectPath, replacements);
    }

    private async Task GenerateGlobalUsingsAsync(
        GenerationPlan plan,
        string blazorProjectPath,
        Dictionary<string, string> replacements)
    {
        string filePath = Path.Combine(blazorProjectPath, "GlobalUsings.cs");
        string content = _templateEngine.Render(GlobalUsingsTemplate, replacements);
        await _fileWriter.WriteGeneratedFileAsync(filePath, content);
    }

    private async Task GenerateImportsRazorAsync(
        string blazorProjectPath,
        Dictionary<string, string> replacements)
    {
        string filePath = Path.Combine(blazorProjectPath, "_Imports.razor");
        string content = _templateEngine.Render(ImportsRazorTemplate, replacements);
        await _fileWriter.WriteGeneratedFileAsync(filePath, content);
    }

    private async Task GenerateAppRazorAsync(
        string blazorProjectPath,
        Dictionary<string, string> replacements)
    {
        string filePath = Path.Combine(blazorProjectPath, "Components", "App.razor");
        string content = _templateEngine.Render(AppRazorTemplate, replacements);
        await _fileWriter.WriteGeneratedFileAsync(filePath, content);
    }

    private async Task GenerateRoutesRazorAsync(
        string blazorProjectPath,
        Dictionary<string, string> replacements)
    {
        string filePath = Path.Combine(blazorProjectPath, "Components", "Routes.razor");
        string content = _templateEngine.Render(RoutesRazorTemplate, replacements);
        await _fileWriter.WriteGeneratedFileAsync(filePath, content);
    }

    private async Task GenerateProgramCsAsync(
        string blazorProjectPath,
        Dictionary<string, string> replacements)
    {
        string filePath = Path.Combine(blazorProjectPath, "Program.cs");
        string content = _templateEngine.Render(ProgramCsTemplate, replacements);
        await _fileWriter.WriteGeneratedFileAsync(filePath, content);
    }

    private const string GlobalUsingsTemplate =
@"// <auto-generated>
// AUTO-GENERATED – DO NOT MODIFY
// Any changes to this file will be overwritten during regeneration.
// </auto-generated>
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.AspNetCore.Components.Routing;
global using Microsoft.AspNetCore.Components.Web;
";

    private const string ImportsRazorTemplate =
@"@* AUTO-GENERATED – DO NOT MODIFY *@
@using System.Net.Http
@using Microsoft.AspNetCore.Components.Forms
@using Microsoft.AspNetCore.Components.Routing
@using Microsoft.AspNetCore.Components.Web
@using Microsoft.AspNetCore.Components.Web.Virtualization
@using Microsoft.JSInterop
@using {{NamespaceRoot}}.Blazor
@using {{NamespaceRoot}}.Blazor.Layout
@using {{NamespaceRoot}}.Blazor.Pages
";

    private const string AppRazorTemplate =
@"@* AUTO-GENERATED – DO NOT MODIFY *@
<!DOCTYPE html>
<html lang=""en"">

<head>
    <meta charset=""utf-8"" />
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />
    <base href=""/"" />
    <link rel=""stylesheet"" href=""css/app.css"" />
    <link rel=""stylesheet"" href=""{{SolutionName}}.Blazor.styles.css"" />
    <HeadOutlet @rendermode=""RenderMode.InteractiveServer"" />
</head>

<body>
    <Routes @rendermode=""RenderMode.InteractiveServer"" />
    <script src=""_framework/blazor.web.js""></script>
</body>

</html>
";

    private const string RoutesRazorTemplate =
@"@* AUTO-GENERATED – DO NOT MODIFY *@
<Router AppAssembly=""typeof(Program).Assembly"">
    <Found Context=""routeData"">
        <RouteView RouteData=""routeData"" DefaultLayout=""typeof(Layout.MainLayout)"" />
        <FocusOnNavigate RouteData=""routeData"" Selector=""h1"" />
    </Found>
</Router>
";

    private const string ProgramCsTemplate =
@"// <auto-generated>
// AUTO-GENERATED – DO NOT MODIFY
// Any changes to this file will be overwritten during regeneration.
// </auto-generated>
using {{NamespaceRoot}}.Blazor.Components;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

WebApplication application = builder.Build();

if (!application.Environment.IsDevelopment())
{
    application.UseExceptionHandler(""/Error"");
    application.UseHsts();
}

application.UseHttpsRedirection();
application.UseStaticFiles();
application.UseAntiforgery();

application.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

application.Run();
";
}
